try
{
	${3}
}
catch (${1}Exception $${2:e})
{
}
